# Generated by Django 2.0 on 2019-06-27 06:28

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogs_descript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('url', models.CharField(max_length=100, verbose_name='唯一URL')),
                ('blog_num', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=mdeditor.fields.MDTextField(null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='descript',
            field=models.CharField(max_length=1000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='url',
            field=models.CharField(max_length=100, verbose_name='唯一URL'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='views',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='分类'),
        ),
    ]
